### ISSUE TITLE
Automate CTAN upload

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/tikz-trackschematic#14]
reuse pgf-tikz action:
https://github.com/pgf-tikz/actions/tree/master/ctan-upload

**Comment by apriljunge** [comment]
An example of how the workflow is applied:
https://github.com/pgf-tikz/pgf-pie/blob/master/.github/workflows/main.yml

**Comment by apriljunge** [comment]
pgf-pie signs its zips with a GPG key.
Do you think this is necessary?

**Comment by kaat0** [comment]
Code signage seems necessary to me. So, we should add it to the list!

- [ ] signing zips with a GPG key.

**Comment by kaat0** [comment]
implemented with https://github.com/railtoolkit/tikz-trackschematic/commit/04fbc5a07cd6ce4f6b272af401305d11306c7a9c
(but currently without code signing)
