### ISSUE TITLE
test for ImageMagick policy to allow pdf->png conversion in testing.sh

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/tikz-trackschematic#19]

**Comment by kaat0** [comment]
@apriljunge what was your workaround whit the png-converter? Did you modify the comparison in the test script for the workaround, as well?

**Comment by apriljunge** [comment]
I converted both pdfs to pngs and compared them with imagemagick

**Comment by kaat0** [comment]
which tool did you use for the conversion? pdftoppm (poppler-utils)?

**Comment by kaat0** [comment]
included in https://github.com/railtoolkit/tikz-trackschematic/commit/cc0c6306f07225610d550a1960baf7d2110407a0
