### ISSUE TITLE
Enhance script usage description

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/tikz-trackschematic#20]
The information scripts give about their parameter didn't help me very much: "Usage: dev-install.sh [-q] [-b]".
Maybe this could be enhanced a little.

**Comment by kaat0** [comment]
what about now?
see https://github.com/railtoolkit/tikz-trackschematic/commit/9b8ae101cdf95762a54f542d039ededdbd7c93d6

**Comment by apriljunge** [comment]
Itˋs Perfect now! Thank you 🥳
