### ISSUE TITLE
Enhance developement documentation

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/tikz-trackschematic#21]
Give short introduction in commands, what you need installed etc. Could be in CONTRIBUTING.md oder README.md

**Comment by apriljunge** [comment]
The following brief notes would be helpful:
- tikz-trackschematic should be regularly installed via TikZ Live
- For developement, `sudo ./build.sh --local-dev-install` should be run. Then the command `\usepackage[dev]{tikz-trackschematic}` loads the files out of src folder
- Tests can be run via `./build.sh --test`

**Comment by kaat0** [comment]
included in f52dc6c405f1e5a3aa951bc53b0aadae421100e5
