### ISSUE TITLE
Undocumented slipturnout option: points=moving

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/tikz-trackschematic#4]
For the options `forward points` and `backward points` in sliptournouts only the values `left` and `right` are documented .
Additional to these two, the value `moving` is implemented and works. Is it missing in the docs? Or is this intentional? 

https://github.com/railtoolkit/tikz-trackschematic/blob/085023f70cb0ee54a8d998eed39ba71072e865c5/src/tikzlibrarytrackschematic.topology.code.tex#L461-L467

https://github.com/railtoolkit/tikz-trackschematic/blob/085023f70cb0ee54a8d998eed39ba71072e865c5/src/tikzlibrarytrackschematic.topology.code.tex#L488-L493

**Comment by kaat0** [comment]
It is missing in the docs! But also for standard turnout.

**Comment by kaat0** [comment]
fixed it
